### ISSUE TITLE
Check if your code is detected by RepoSense

### ISSUE THREAD

**Issue by damithc** [CS2103-AY1819S1-W12-4/main#49]
Guys, see https://github.com/nus-cs2103-AY1819S1/forum/issues/74

**Comment by spencertan96** [comment]
Alright! My code is not getting detected by RepoSense, I'll try installing RepoSense over the weekend and fix it

**Comment by robertvictoreen** [comment]
Thanks, only some of my code has been detected.

**Comment by damithc** [comment]
> Thanks, only some of my code has been detected.

@robertvictoreen follow the instructions in the linked post to rectify the problem.

**Comment by spencertan96** [comment]
OK my RepoSense is working now!
